name: Run MATLAB Script

on:
  push:
    branches:
      - main

jobs:
  run-matlab-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up MATLAB
      uses: mathworks/matlab-actions/setup@v0

    - name: Run MATLAB Script
      run: |
        matlab -batch "Experiment01/Untitled5.m"
